version: '3'
services:  
  h5p-library-pusher:
    image: sr258/h5p-library-pusher:0.1.0
    restart: unless-stopped
    volumes:
    - library-cache:/usr/src/app/working_dir
    - h5p-config:/usr/src/app/h5p-config
    environment:
    - H5P_CONFIG=/usr/src/app/h5p-config/h5p-config.json
    - H5P_WORKING_DIR=/usr/src/app/working_dir
volumes:
  library-cache: {}
  h5p-config: {}